# Generated by Django 4.2.4 on 2023-09-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_rename_unit_price_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='unit_price',
        ),
    ]
